# Generated by Django 5.0.2 on 2024-02-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('salary', models.FloatField()),
                ('company', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
    ]
